server:
    port: 80
    context-path: #/livingmanage/

spring:
    datasource:
        name: qurich_information
        url: jdbc:mysql://127.0.0.1:3306/qurich_information?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: mysql
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#spring.view.prefix=/WEB-INF/jsp/
#spring.view.suffix=.jsp
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
freemarker:
            allowRequestOverride: false
            allowSessionOverride: false
            requestContextAttribute: request
            cache: false
            checkTemplateLocation: true
            contentType: text/html
            exposeRequestAttributes: true
            exposeSessionAttributes: false
            exposeSpringMacroHelpers: false
            suffix: .ftl
            templateEncoding: UTF-8
            templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
            spring.freemarker.settings: 
                locale: zh_CN
                date_format: yyyy-MM-dd
                time_format: HH:mm:ss
                datetime_format: yyyy-MM-dd HH:mm:ss	

mybatis:
    type-aliases-package: com.qurich.external.model
    type-handlers-package: com.qurich.external.mapper
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30


